### ISSUE TITLE
Ctrl+F text if selected becomes invisible for me.

### ISSUE THREAD

**Issue by Realife-Brahmin** [BlueRexPY/ChristmasNight#1]
![1](https://github.com/user-attachments/assets/e7a00bd0-cebb-4715-be8b-2840c939dc8e)
Written text in the 'Find' search box
![2](https://github.com/user-attachments/assets/9ce08eb1-3c3c-4640-9e0e-d14350d3b5e7)
The same text but _selected_

**Comment by BlueRexPY** [comment]
Good catch!

Thank you for bringing this issue to our attention.

A [PR][https://github.com/BlueRexPY/ChristmasNight/pull/2] has been just merged and deployed to the Marcketplace.

Please let us know if you experience any further issues or if the fix doesn't resolve the problem completely. Thnaks 🤗.

(ps. please restart extention to see changes)
![image](https://github.com/user-attachments/assets/0ded61a0-2dca-4bbb-b8c3-ff763bb7b6be)

**Comment by Realife-Brahmin** [comment]
![image](https://github.com/user-attachments/assets/61229948-6fec-4726-9821-f0069b8914e4)
Nice! Thanks a lot!
